services:
  laser-arena-1:
    build: .
    image: laser-arena:latest
    container_name: laser-arena-1
    restart: unless-stopped
    environment:
      - PORT=3000
      - MAX_PLAYERS=40
    ports:
      - "3000:3000"

  laser-arena-2:
    image: laser-arena:latest
    container_name: laser-arena-2
    depends_on:
      - laser-arena-1
    restart: unless-stopped
    environment:
      - PORT=3000
      - MAX_PLAYERS=40
    ports:
      - "3001:3000"
